---
- hosts: osmo
  gather_facts: no
  become: yes
  tasks:

    - name: Install packages for building
      apt:
        name: build-essential,libtool,libtalloc-dev,libsctp-dev,shtool,autoconf,automake,git-core,pkg-config,make,gcc,gnutls-dev,shtool,git-core,libmnl-dev,libpcsclite-dev,libpcsclite1,libusb-1.0-0-dev,libusb-1.0-0
        state: present
        update_cache: yes

    - name: Clone libosmocore from gitea.osmocom.org
      git:
        repo: https://gitea.osmocom.org/osmocom/libosmocore.git
        dest: ~/repos/libosmocore/
        clone: yes
        update: yes

    - name: Clone OsmocomBB from gitea.osmocom.org
      git:
        repo: https://gitea.osmocom.org/phone-side/osmocom-bb.git
        dest: ~/repos/osmocom-bb/
        clone: yes
        update: yes

    - name: Clone Osmo-bts from Github
      git:
        repo: https://github.com/osmocom/osmo-bts
        dest: ~/repos/osmo-bts/
        clone: yes
        update: yes

    - name: Clone libosmo-gprs from Github
      git:
        repo: https://github.com/osmocom/libosmo-gprs.git
        dest: ~/repos/libosmo-gprs/
        clone: yes
        update: yes

    - name: Build libosmocore
      command: "{{ item }}"
      args:                                                                     
        chdir: ~/repos/libosmocore
        creates: /usr/local/lib/libosmocore.so
      with_items:
        - "autoreconf -i"
        - "./configure"
        - "make"
        - "make install"
        - "ldconfig -i"

    - name: Build libosmo-gprs
      command: "{{ item }}"
      args:
        chdir: ~/repos/libosmo-gprs
        creates: /usr/local/lib/libosmo-gprs-rlcmac.so
      with_items:
        - "autoreconf -i"
        - "./configure"  
        - "make"
        - "make install"

    - name: Build mobile from osmocom-bb
      command: "{{ item }}"
      args:
        chdir: ~/repos/osmocom-bb/src/host/layer23
        creates: /usr/local/bin/mobile
      with_items:
        - "autoreconf -i"
        - "./configure"
        - "make"
        - "make install"

    - name: Build virtphy from osmocom-bb
      command: "{{ item }}"
      args:
        chdir: ~/repos/osmocom-bb/src/host/virt_phy
        creates: /usr/local/bin/virtphy
      with_items:
        - "autoreconf -i"
        - "./configure"
        - "make"
        - "make install"

    - name: Install osmo related packages
      apt:
        name: osmo-hlr,osmo-msc,osmo-mgw,osmo-bsc,osmo-bts,osmo-stp
        state: present
        update_cache: yes

    - name: Start HLR
      systemd:
        name: osmo-hlr
        state: started
        daemon_reload: yes
        enabled: yes

    - name: Start STP
      systemd:
        name: osmo-stp
        state: started
        daemon_reload: yes
        enabled: yes

    - name: Start MGW
      systemd:
        name: osmo-mgw
        state: started
        daemon_reload: yes
        enabled: yes

    - name: Start MSC
      systemd:
        name: osmo-msc
        state: started
        daemon_reload: yes
        enabled: yes

    - name: Start BSC
      systemd:
        name: osmo-bsc
        state: started
        daemon_reload: yes
        enabled: yes

    - name: Copy service file for virtual BTS
      copy:
        src: ~/repos/osmo-bts/contrib/systemd/osmo-bts-virtual.service
        dest: /lib/systemd/system/osmo-bts-virtual.service
        owner: root
        group: root
        mode: 644
        remote_src: yes

    - name: Copy configfile for virtual BTS
      copy:
        src: ~/repos/osmo-bts/doc/examples/virtual/osmo-bts-virtual.cfg
        dest: /etc/osmocom/osmo-bts-virtual.cfg
        owner: root
        group: root
        mode: 644 
        remote_src: yes
    - name: Change basic config for virtual BTS
      lineinfile:
        path: /etc/osmocom/osmo-bts-virtual.cfg
        regexp: '^ ipa unit-id'
        line: ' ipa unit-id 1800 0'

    - name: Start BTS-virtual
      systemd:
        name: osmo-bts-virtual
        state: restarted
        daemon_reload: yes
        enabled: yes

    - name: Copy configfile for virtual MSs
      copy:
        src: ~/repos/osmocom-bb/doc/examples/mobile/default.cfg
        dest: /etc/osmocom/mobile.cfg
        owner: root
        group: root
        mode: 644
        remote_src: yes

#    - name: Add subscribers to HLR
#      telnet:
#        host: 127.0.0.1
#        port: 4258
#        prompts:
#          - 'OsmoHLR[>#]'
#        command:
#          - ena
#          - subscriber imsi 001010000000001 create
#          - subscriber imsi 001010000000002 create
#          - subscriber id 1 update aud2g comp128v1 ki 00000000000000000000000000000000
#          - subscriber id 1 update msisdn 555501
#          - subscriber id 2 update aud2g comp128v1 ki 00000000000000000000000000000000
#          - subscriber id 2 update msisdn 555502
     
    - name: Configure IMEI for mobile
      lineinfile:
        path: /etc/osmocom/mobile.cfg
        regexp: '^ imei 000000000000000 0'
        line: ' imei 000000000000001 0'

    - name: Configure IMSI for mobile
      lineinfile:
        path: /etc/osmocom/mobile.cfg
        regexp: '^  imsi 001010000000000'
        line: '  imsi 001010000000001'

    - name: Configure SIM for mobile
      lineinfile:
        path: /etc/osmocom/mobile.cfg
        regexp: '^ sim reader'
        line: ' sim test'

